### ISSUE TITLE
关于配置

### ISSUE THREAD

**Issue by youkale** [wenj91/gobatis#28]
大致看了下代码，感觉简洁明了
有几个地方感觉需要改进:
1.数据库连接(池)的初始化，觉得不应该耦合在代码里面，是通过外部传入。
2.同时读取yaml相关的代码也不应该在里面，而是通过外部传入

**Comment by wenj91** [comment]
1. 连接池初始化通过外部传入, 意思是连接池应该由用户进行自己实现吗?
目前golang sql驱动是自带数据库连接池的, 我目前的做法就是想直接使用golang本身的连接池, 这样用户就没必要自己实现, 以免走入误区
2. 这个yaml配置读取目前我感觉是就几点固定配置, 用户使用的时候如果自己实现读取配置就感觉有点啰嗦, 这点的话后面我看看是去掉,然后由用户实现, 还是再拓展可选

**Comment by youkale** [comment]
1. 数据库默认都是外部帮忙实例化好的，有可能他还有其他的orm框架在共用，或者其他的一些优化的参数。 建议是之要耦合sql.DB即可
2. 因为这个项目不是单独 用来跑的项目，一般是嵌入在其他工程(应用)里的,有可能别人用的是ini文件或者toml或者json,如果这里再有一个yaml感觉会多余，建议使用一个struct，让开放者传入,这样就不耦合配置文件（json,yaml,ini）了。

**Comment by wenj91** [comment]
嗯, 你说这个我明白了, 之后有空会拓展代码配置方式, 同时也会保留现有的配置方式, 供用户自己选择

**Comment by wenj91** [comment]
配置已经调整回来了， 另外新增代码配置方法
