### ISSUE TITLE
返回值自动映射

### ISSUE THREAD

**Issue by youkale** [wenj91/gobatis#31]
目前返回值都是通过field的tag映射的，我在想是否考虑将  CamelCase 自动转换为 snake_case

**Comment by wenj91** [comment]
目前感觉这个其实没必要, 因为字段命名方式虽然一般都是下划线风格, 但是还是有些人喜欢用驼峰风格的, 所以自动帮别人转换反而不太好

**Comment by wenj91** [comment]
对了, 最近有些忙, 有些问题不能及时回复, 还有之前你提交的代码我也有些看法, 目前是不能直接合并到主分支的, 如果你愿意请发送你邮箱地址到我邮箱, 我给你说下我的一些想法, 还有一些后续维护的问题

**Comment by wenj91** [comment]
我邮箱在我主页有

**Comment by youkale** [comment]
发了个邮件给你，你看一下
