### ISSUE TITLE
事务怎么处理的？

### ISSUE THREAD

**Issue by xwinie** [wenj91/gobatis#41]
多个 insert或者update的事务怎么处理

**Comment by wenj91** [comment]
// 事务示例
	tx, _ := gb.Begin()
	defer tx.Rollback()

    // 插入1
	_, _, err := tx.Insert("xxxx0", xxx)
    if  nil != err {
        return err
    }

    // 插入2
    _, _, err := tx.Insert("xxxx1", xxx)
    if  nil != err {
        return err
    }

	// 提交事务
	tx.Commit()

**Comment by wenj91** [comment]
现在也可以这样
gb.Transaction(func (tx *gobatis.TX) error{
    // 插入1
     _, _, err := tx.Insert("xxxx0", xxx)
    if  nil != err {
       return err
    }

    // 插入2
    _, _, err := tx.Insert("xxxx1", xxx)
    if  nil != err {
        return err
    }
    return nil
})
