### ISSUE TITLE
pointer fields of a struct object may cause panic while inserting new records

### ISSUE THREAD

**Issue by Janisonllz** [wenj91/gobatis#43]
问题描述: 用结构体插入记录场景下，如果结构体内包含*time.Time类型字段会panic
报错位置: proc_params.go:75
相关函数: structToMap, fieldToVal, etc.

**Comment by Janisonllz** [comment]
额外一条建议：插入结构体时可否考虑使用tag中指定的字段名呢？使用时会灵活很多

**Comment by wenj91** [comment]
1. 目前是不支持结构体指针类型，你可以用NullTime NullBool NullFloat64   NullInt64   NullString达到相同目的，后续是否会增加指针类实现很难说，精力目前不在这;
2. 你说的应该是数据结构对表字段吧，这个目前是可以的，比如：
```go
type User struct {
	Id    gobatis.NullInt64  `field:"id"`
	Name  gobatis.NullString `field:"name"`
	Email gobatis.NullString `field:"email"`
	CrtTm gobatis.NullTime   `field:"crtTm"`
}
```
这里tag field就是结构体属性对应表字段了；

**Comment by Janisonllz** [comment]
> 额外一条建议：插入结构体时可否考虑使用tag中指定的字段名呢？使用时会灵活很多

我的意思是通过入参为结构体的方式插入数据库，具体位置是proc_params.go:128(函数：structToMap)
比如可以改成下面这种？
```
		objType := objVal.Type()
		for i := 0; i < objVal.NumField(); i++ {
			fieldVal := objVal.Field(i)
			if fieldVal.CanInterface() {
				field := objType.Field(i)
				// ###### modify start
				// res[field.Name] = fieldToVal(fieldVal.Interface())
				tag := field.Tag.Get("field")
				if tag != "" {
					if tag != "-" {
						res[tag] = fieldToVal(fieldVal.Interface())
					}
				} else {
					res[field.Name] = fieldToVal(fieldVal.Interface())
				}
				// ###### modify end
			}
		}
```

**Comment by wenj91** [comment]
我在想这样能带来什么便利吗，
因为mapper是要手写的，
以这个struct为例
```go
type User struct {
	Id    gobatis.NullInt64  `field:"id"`
	Name  gobatis.NullString `field:"name"`
	Email gobatis.NullString `field:"email"`
	CrtTm gobatis.NullTime   `field:"crtTm"`
}
```
比如我要插入一个user
那么我对应是要写,
```xml
<insert id="saveUser">
        insert into user (name, email, crtTm)
        values (#{Name}, #{Email}, #{CrtTm})
</insert>
```
这里的#{Name}...中的Name还有Email都是struct的属性名称，
```xml
<insert id="saveUser">
        insert into user (name, email, crtTm)
        values (#{name}, #{email}, #{crtTm})
</insert>
```
但是如果按照你说那样的话
那要写成标签field的名称，像驼峰标识还好看点，如果是那种蛇形命名风格的话如crt_tm被标识为#{crt_tm}
这样看起来怪怪的😂

**Comment by Janisonllz** [comment]
``` golang
type User struct {
	Id    gobatis.NullInt64  `field:"id"`
	Name  gobatis.NullString `field:"name"`
	Email gobatis.NullString `field:"email"`
	CrtTm gobatis.NullTime   `field:"crtTm"`
}
```
引用你前面贴出来的这个代码。既然Select查询参数为结构实体时是通过tag进行的映射，那么为何不在Insert插入结构体时同样使用tag映射呢？感觉这样会好理解一些。

**Comment by wenj91** [comment]
如果从理解上来说确实比较直接

**Comment by wenj91** [comment]
> > 额外一条建议：插入结构体时可否考虑使用tag中指定的字段名呢？使用时会灵活很多
> 
> 我的意思是通过入参为结构体的方式插入数据库，具体位置是proc_params.go:128(函数：structToMap)
> 比如可以改成下面这种？
> 
> ```
> 		objType := objVal.Type()
> 		for i := 0; i < objVal.NumField(); i++ {
> 			fieldVal := objVal.Field(i)
> 			if fieldVal.CanInterface() {
> 				field := objType.Field(i)
> 				// ###### modify start
> 				// res[field.Name] = fieldToVal(fieldVal.Interface())
> 				tag := field.Tag.Get("field")
> 				if tag != "" {
> 					if tag != "-" {
> 						res[tag] = fieldToVal(fieldVal.Interface())
> 					}
> 				} else {
> 					res[field.Name] = fieldToVal(fieldVal.Interface())
> 				}
> 				// ###### modify end
> 			}
> 		}
> ```

你这个如果调整了，可以提一个pr，我今天有空调整一下，改成既可以用结构体属性名做参数也可以按照tag来做参数
